export enum PoolChipColor {
  RED = "RED", PINK = "PINK", PURPLE = "PURPLE", DEEP_PURPLE = "DEEP_PURPLE", BLUE = "BLUE",
  INDIGO = "INDIGO", LIGHT_BLUE = "LIGHT_BLUE", CYAN = "CYAN", TEAL = "TEAL",
  GREEN = "GREEN", LIGHT_GREEN = "LIGHT_GREEN", LIME = "LIME", YELLOW = "YELLOW",
  ORANGE = "ORANGE"
}